#!/bin/sh
# vim: smartindent tabstop=4 shiftwidth=4 expandtab number
#
#   Set up to create the cma.centos docker image and extract the packages it creates
#   These include both the Assimilation packages and also the libsodium packages
#   These packages are extracted into the 'packages' subdirectory
#
#
# This file is part of the Assimilation Project.
#
# Author: Alan Robertson <alanr@unix.sh>
# Copyright (C) 2014 - Assimilation Systems Limited
#
# Free support is available from the Assimilation Project community - http://assimproj.org
# Paid support is available from Assimilation Systems Limited - http://assimilationsystems.com
#
# The Assimilation software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Assimilation software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Assimilation Project software.  If not, see http://www.gnu.org/licenses/
#
#
#
#
set -e 
ARGS="$*"
cd $1
YUM='yum -y'
shift

NEOVERS=3.0.1
NEOCONF=/etc/neo4j
NEOEDITION=community
PY2NEOVERS=2.0.8
JRE=java-1.8.0-openjdk-headless
CENTOSREL=$(basename $PWD)
NANONAME="assimilation/nanoprobe-$CENTOSREL"
CMANAME="assimilation/cma-$CENTOSREL"
DOCKERFILE="$PWD/../Dockerfile"
NANOFILE="$PWD/../nanoDockerfile"
CMAFILE="$PWD/../cmaDockerfile"
# Note that we just use the one we wrote for Ubuntu...
STARTFILE="$PWD/../../Ubuntu/cmaStart"

BUILD="assimilation/build_centos_$CENTOSREL"
LOCALWS=$HOME/monitor/src
PKGDIR=$(pwd)
rm -fr local

EFLAG=''

case $1 in
  local) 
        mkdir local
        cd local
        pwd
        GITHASH=$(git rev-parse --short master)
        (D=$PWD; cd ../../../.. && git archive --prefix=src/ -o $D/tip.tar.gz HEAD)
        cat $DOCKERFILE |
        sed -e 's%ENV GITTARZAN .*%ENV GITTARZAN tip.tar.gz%g'  \
            -e "s%centos:latest%centos:$CENTOSREL%g" $EFLAG     \
            -e "s%^ENV GITHASH .*%ENV GITHASH $GITHASH%g"       \
            -e 's%^RUN.* mv .*ssimilation-.*%# &%'              \
            -e "s%@NEOVERS@%${NEOVERS}%g"                       \
            -e "s%@NEOCONF@%${NEOCONF}%g"                       \
            -e "s%@NEOEDITION@%${NEOEDITION}%g"                 \
            -e "s%@PY2NEOVERS@%${PY2NEOVERS}%g"                 \
            -e "s%@YUM@%${YUM}%g"                               \
            -e "s%@JRE@%${JRE}%g"                               \
            -e "s%@OURDATE@%$(date)g"                           \
            -e 's%@ARCH@%x86_64%g'                              \
            -e 's%RUN service rsyslog start.*testify%#&%'       \
            > Dockerfile
        ;;
    *)  GITHASH=$(git rev-parse --short HEAD)
        cat $DOCKERFILE |                                       \
            sed -e "s%centos:latest%centos:$CENTOSREL%g" $EFLAG \
            -e "s%^ENV GITHASH .*%ENV GITHASH $GITHASH%g"       \
            -e "s%@YUM@%${YUM}%g"                               \
            -e "s%@JRE@%${JRE}%g"                               \
            -e "s%@NEOVERS@%${NEOVERS}%g"                       \
            -e "s%@NEOCONF@%${NEOCONF}%g"                       \
            -e "s%@NEOEDITION@%${NEOEDITION}%g"                 \
            -e "s%@PY2NEOVERS@%${PY2NEOVERS}%g"                 \
            -e 's%@ARCH@%x86_64%g'                              \
            -e "s%@OURDATE@%$(date)%g" > Dockerfile
        ;;
esac
grep 'FROM.*centos:' Dockerfile

cp /etc/timezone .
docker build -t $BUILD .
rm -fr timezone $PKGDIR/packages
ID=$(docker run -d $BUILD /bin/sleep 5)
# Note that it will include the last part of the from pathname under the to path...
docker cp $ID:/root/assimilation/packages $PKGDIR
echo "Build of $ARGS BUILD complete."
