#!/bin/sh
# vim: smartindent tabstop=4 shiftwidth=4 expandtab number
#
# This file is part of the Assimilation Project.
#
# Author: Alan Robertson <alanr@unix.sh>
# Copyright (C) 2014 - Assimilation Systems Limited
#
# Free support is available from the Assimilation Project community - http://assimproj.org
# Paid support is available from Assimilation Systems Limited - http://assimilationsystems.com
#
# The Assimilation software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Assimilation software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Assimilation Project software.  If not, see http://www.gnu.org/licenses/
#
#
#
#
TMP=$(mktemp)
trap 'rm -fr ${TMP}' 0
sudo docker.io build . | tee $TMP
lastline=$(tail -1 $TMP)
set - ${lastline}
case $1 in
    [Ss]uccessfully);;
    *)     echo 'Docker build failed.'; exit 1;;
esac
lastdock=$3
docker.io run -i -t -v /dev/fuse:/dev/fuse -v /dev/log:/dev/log "$3" /bin/bash /root/assimilation/src/docker/Ubuntu/post-build.sh

