#!/bin/sh -eu
# vim: smartindent tabstop=4 shiftwidth=4 expandtab number colorcolumn=80
#
# Program for testing our magical 'installme' script in different
# Linux environments
#
# This file is part of the Assimilation Project.
#
# Author: Alan Robertson <alanr@unix.sh>
# Copyright (C) 2015 - Assimilation Systems Limited
#
# Free support is available from the Assimilation Project community
#   - http://assimproj.org
# Paid support is available from Assimilation Systems Limited
#   - http://assimilationsystems.com
#
# The Assimilation software is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Assimilation software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Assimilation Project software.
# If not, see http://www.gnu.org/licenses/
#

setup() {
    LOGGER=rsyslog
    cp ../../buildtools/installme .
    case $1 in
        *centos*|*fedora*)  INSTALLER=yum;;
        *ubuntu*|*debian*)  INSTALLER=apt-get;;
    esac
    cat <<-! > Dockerfile
		FROM $1
		ENV WORK /tmp/workdir
		RUN mkdir /tmp/workdir
		WORKDIR /tmp/workdir
		RUN : "Version $(date)"
		ADD installme /tmp/workdir/
		RUN chmod 755 installme
		RUN ls -l \$WORK
		#RUN $INSTALLER -q -y install ${LOGGER}
		RUN /bin/sh -ex installme $2
		!
}

ubupairs="ubuntu:vivid ubuntu:trusty ubuntu:precise ubuntu:wily" 
debpairs="debian:wheezy debian:jessie"
fedpairs="fedora:21 fedora:22"
centpairs="centos:centos6 centos:centos7"

for pairs in $debpairs $fedpairs $centpairs $ubupairs
do
    for role in cma # nanoprobe # test
    do
        # Java dependency currently prohibits clean cma install with RPMs
        # But RPMs might not be the best choice.
        case $pairs:$role in
            fedora:*:cma)   continue;;
        esac
        setup $pairs $role
        echo "TEST FOR $pairs in role $role STARTED $(date)"
        if
            time docker build . > ${pairs}.${role}.out 2>&1
        then
            echo "TEST FOR $pairs in role $role COMPLETE $(date)"
        else
            echo "TEST FOR $pairs in role $role FAILED $(date)"
        fi
    done
done
