#!/bin/bash
# vim:ts=4:sw=4:softtabstop=4:smarttab:expandtab
set -eu -o pipefail
for directory in meson nanoprobe
do
    (
        echo "================= Building $directory docker container ================="
        cd $directory
        ./dockit  "$@"
        echo ""
    )
done | tee -i dockit.out
