# vim:ts=4:sw=4:softtabstop=4:smarttab:expandtab
from @MESON_TAG@
#
ENV PYCMD=python3.6
# PYCMD must match the version installed in the @MESON_TAG@ container
ENV LIBSODIUM_VERSION=1.0.18
ENV LIBPCAP_VERSION=1.9.1
#
RUN mkdir -p /tmp/build/src
WORKDIR /tmp/build/src
RUN ${PYCMD} --version
#
# Compile libsodium - because we want a reasonably recent version 
# @TODO: Validate the source tar ball signature
#
ENV LIBSODIUM_BASEURL=https://download.libsodium.org/libsodium/releases/libsodium-
ENV LIBSODIUM_URL=${LIBSODIUM_BASEURL}${LIBSODIUM_VERSION}.tar.gz
ENV LIBSODIUM_SIG=${LIBSODIUM_URL}.sig
RUN wget --quiet ${LIBSODIUM_SIG} ${LIBSODIUM_URL}
RUN tar xzf $(basename ${LIBSODIUM_URL})
RUN  cd libsodium-${LIBSODIUM_VERSION} && ./configure prefix=/usr && make && make check && make install
#
# Compile libpcap - because we need a static (.a) version of the library
# @TODO: Validate the source tar ball signature
#
ENV LIBPCAP_BASEURL=https://www.tcpdump.org/release/libpcap-
ENV LIBPCAP_URL=${LIBPCAP_BASEURL}${LIBPCAP_VERSION}.tar.gz
ENV LIBPCAP_SIG=${LIBPCAP_URL}.sig
RUN wget --quiet ${LIBPCAP_SIG} ${LIBPCAP_URL}
RUN tar xzf $(basename ${LIBPCAP_URL})
RUN  cd libpcap-${LIBPCAP_VERSION} && ./configure prefix=/usr && make && make install
#
# Install other os-provided packages we need
#
RUN yum -y install pkgconfig-devel glib2-devel glib2-static zlib-devel zlib-static
#
# Now bring in the Assimilation C source and compile it...
#
ADD meson.build /tmp/build/src/
ADD src/cma/frameinfo.py /tmp/build/src/cma
ENV PKG_CONFIG_PATH /usr/local/lib/pkgconfig/
ADD src/ /tmp/build/src/
RUN time /usr/local/bin/meson /tmp/build/bin/
WORKDIR /tmp/build/bin
RUN time /usr/local/bin/ninja
RUN sha256sum /tmp/build/bin/nanoprobe /tmp/build/bin/*.so /tmp/build/bin/*.a | tee sums
