#!/bin/sh
# vim: smartindent tabstop=4 shiftwidth=4 expandtab number
#
#	dockit - generate Dockerfile for CentOS6 builds
#
# This file is part of the Assimilation Project.
#
# Author: Alan Robertson <alanr@unix.sh>
# Copyright (C) 2014 - Assimilation Systems Limited
#
# Free support is available from the Assimilation Project community - http://assimproj.org
# Paid support is available from Assimilation Systems Limited - http://assimilationsystems.com
#
# The Assimilation software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Assimilation software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Assimilation Project software.  If not, see http://www.gnu.org/licenses/
#
#
set -e
DOCKER=docker
CMA=assim.centos6
PKGDIR=$(pwd)/packages
REPO=assimilation/assimilation-official
HASH=$(git ls-remote --heads https://github.com/$REPO | grep refs/heads/master | cut -c1-7)
test ! -z "$HASH"
export ASSIMVERSION="$(echo $REPO | tr '/' '-')-$HASH"
echo "Working with version $ASSIMVERSION"
bash ./CentOS6-directions --format=dockerfile docker > Dockerfile
cat <<'!EOF' >> Dockerfile
RUN echo "GOODBUILD=$(echo "$(lsb_release -i -s)_$(lsb_release -r -s)-$(uname -m)" | tr '[A-Z]' '[a-z]')"
!EOF
rm -fr $PKGDIR/*
$DOCKER build -t $CMA .
ID=$(docker run -d $CMA /bin/sleep 5)
# Note that it will include the last part of the from pathname (i.e. "RPMS") under the to path...
docker cp "$ID:/root/rpmbuild/RPMS/" .
mv RPMS/*/* $PKGDIR
rm -fr RPMS
