# vim:ts=4:sw=4:softtabstop=4:smarttab:expandtab
from @MESON_TAG@
#
ENV PYCMD=python3
# PYCMD must match the version installed in the @MESON_TAG@ container
ENV LIBSODIUM_VERSION=1.0.18
ENV LIBPCAP_VERSION=1.9.1
#
RUN mkdir -p /tmp/build/src/
WORKDIR /tmp/build/src/
ADD src/getsigningkey.py src/hashes.csv /tmp/build/src/
RUN ${PYCMD} --version
#
# Compile libsodium - because we want a reasonably recent version 
#
ENV LIBSODIUM_BASEURL=https://download.libsodium.org/libsodium/releases/libsodium-
ENV LIBSODIUM_URL=${LIBSODIUM_BASEURL}${LIBSODIUM_VERSION}.tar.gz
ENV LIBSODIUM_SIG=${LIBSODIUM_URL}.sig
ENV LIBSODIUM_SIGNING_KEY https://download.libsodium.org/jedi.gpg.asc
RUN pip3 install requests                               # Needed for getsigningkey.py
RUN ${PYCMD} getsigningkey.py ${LIBSODIUM_SIGNING_KEY}  # Fetch and validate signing key...
RUN gpg --import $(basename $LIBSODIUM_SIGNING_KEY)     # Import validated signing key
RUN wget --quiet ${LIBSODIUM_URL} ${LIBSODIUM_SIG}      # Get libsodium and its signature
RUN gpg $(basename ${LIBSODIUM_SIG})                    # Validate libsodium tar ballDD
# NOTE: This will give a warning about not knowing if this is a trusted signature. That's OK...
RUN tar xzf $(basename ${LIBSODIUM_URL})                # untar and install...
RUN cd libsodium-${LIBSODIUM_VERSION} && ./configure prefix=/usr && make && make check && make install
#
# Compile libpcap - because we need a static (.a) version of the library
#
ENV LIBPCAP_BASEURL=https://www.tcpdump.org/release/libpcap-
ENV LIBPCAP_URL=${LIBPCAP_BASEURL}${LIBPCAP_VERSION}.tar.gz
ENV LIBPCAP_SIG=${LIBPCAP_URL}.sig
ENV LIBPCAP_SIGNING_KEY https://www.tcpdump.org/release/signing-key.asc
RUN ${PYCMD} getsigningkey.py ${LIBPCAP_SIGNING_KEY}  # Fetch and validate signing key...
RUN gpg --import $(basename $LIBPCAP_SIGNING_KEY)     # Import validated signing key
RUN wget --quiet ${LIBPCAP_SIG} ${LIBPCAP_URL}
RUN gpg $(basename ${LIBPCAP_SIG})                    # Validate libpcap tar ballDD
# NOTE: This will give a warning about not knowing if this is a trusted signature. That's OK...
RUN tar xzf $(basename ${LIBPCAP_URL})
RUN cd libpcap-${LIBPCAP_VERSION} && ./configure prefix=/usr && make && make install
#
# Install other os-provided packages we need
#
RUN yum -y install pkgconfig-devel glib2-devel glib2-static zlib-devel zlib-static
#
# Now bring in the Assimilation C source and compile it...
#
ADD meson.build /tmp/build/src/
ADD src/cma/frameinfo.py /tmp/build/src/cma
ENV PKG_CONFIG_PATH /usr/local/lib/pkgconfig/
ADD src/ /tmp/build/src/
RUN rm -f /tmp/build/src/include/projectcommon.h
RUN time /usr/local/bin/meson /tmp/build/bin/
WORKDIR /tmp/build/bin
RUN time /usr/local/bin/ninja
RUN cp -a -P /usr/lib/libsodium.* /usr/lib/libpcap.* .
RUN sha256sum nanoprobe libassimilation* libsodium.* libpcap.* frame*type*.h | tee sums
RUN tar czf nanoprobe.tar.gz nanoprobe libassimilation* libsodium.* libpcap.* frame*type*.h sums
