#!/bin/sh
#

#
# Common for all VMs
#

# copy the key for user root
mkdir -p ~root/.ssh
cp ~vagrant/.ssh/authorized_keys ~root/.ssh

# the cores directory
mkdir -p /tmp/cores
chmod 777 /tmp/cores

# rsyslog configuration
PARENT=$(/sbin/route -n | grep '^0\.0\.0\.0' | cut -c17-32)
PARENT=$(echo $PARENT)
echo '*.*   @@'"${PARENT}:514" > /etc/rsyslog.d/99-remote.conf
