#!/bin/sh
#

echo "dbms.connector.http.address=0.0.0.0:7474" >> /etc/neo4j/neo4j.conf
echo "cypher.forbid_shortestpath_common_nodes=false" >> /etc/neo4j/neo4j.conf
# py2neo wants the config elsewhere
mkdir -p /usr/share/neo4j/conf
ln -s /etc/neo4j/neo4j.conf /usr/share/neo4j/conf
chown -R neo4j /usr/share/neo4j/conf
rm -fr /var/lib/neo4j/data/databases/graph.db /var/lib/neo4j/data/dbms/auth
service neo4j start; sleep 10
assimcli genkeys
rm -f "/usr/share/assimilation/crypto.d/#CMA#00001.secret"
assimcli neo4jpass neo4j2
service neo4j stop
