#!/bin/sh
#

apt-get -y update
apt-get -y install --no-install-recommends rsyslog net-tools dtach tcpdump
apt-get -y install --no-install-recommends /vagrant/libsodium_*.deb /vagrant/assimilation-nanoprobe_*.deb
