#!/bin/sh
#

NEOREL=3.2.6
neoversion=stable
PY2NEOREL=3.1.2

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
apt-get -y update
apt-get -y install --no-install-recommends gnupg wget python-setuptools python-pip python-netaddr lsb-release iproute2 adduser
pip install "py2neo==$PY2NEOREL" getent inject dpath
wget -q -O - http://debian.neo4j.org/neotechnology.gpg.key | apt-key add - 
echo "deb http://debian.neo4j.org/repo ${neoversion}/" > /etc/apt/sources.list.d/neo4j.list
apt-get -y update
apt-get -y install --no-install-recommends neo4j=$NEOREL
apt-get -y install --no-install-recommends /vagrant/assimilation-cma_*.deb
