# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

if ENV['NUM_NANOPROBES']
	N = ENV['NUM_NANOPROBES'].to_i
else
	N = 1
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_check_update = FALSE
  #config.vm.network "private_network", type: "dhcp"
  config.apt_proxy.http = "http://10.0.2.2:3142"
  config.apt_proxy.https = "DIRECT"
  config.vm.define "cma" do |cma|
	  cma.vm.hostname = "cma"
	  cma.vm.provision :shell, path: "install_nanoprobe"
	  cma.vm.provision :shell, path: "install_cma"
  end
  (1..N).each do |i|
	  config.vm.define "nanoprobe#{i}" do |nanoprobe|
		  nanoprobe.vm.hostname = "nanoprobe#{i}"
		  nanoprobe.vm.provision :shell, path: "install_nanoprobe"
	  end
  end
end
