#!/bin/sh
#
# Command to discover our current ARP cache data.
# Note that it is good to merge different samples of the ARP cache over time.
#
#
# @author &copy; 2012 - Alan Robertson <alanr@unix.sh>
# @n
# Licensed under the GNU General Public License (GPL) version 3 or any later version at your option.

#
ARP_N='arp -n'

# Discover ARP cache data
discover() {
    cat <<-!
	{
	  "discovertype": "arpcache",
	  "description": "ARP cache snapshot",
	  "host": "$(uname -n)",
	  "source": "$0",
	  "data": {
	!
    # Parse arp -n output
    comma='    '
    arp -n | awk '{print $1,$3,$5}' | sort -u |
    while 
      read ipaddr macaddr nic
    do
      case $macaddr in
        *:*:*)	;;
        *)	continue;;
      esac
      printf '%s"%s":\t{"mac": "%s", "nic": "%s"}' "$comma" "$ipaddr" "$macaddr" "$nic"
      comma=',
    '
    done
    printf '\n  }\n}\n'
}
discover
