#!/bin/sh
# vim: smartindent shiftwidth=2 number
#
# This file is part of the Assimilation Project.
#
# Author: Alan Robertson <alanr@unix.sh>
# Copyright (C) 2013,2014 - Assimilation Systems Limited
#
# Free support is available from the Assimilation Project community - http://assimproj.org
# Paid support is available from Assimilation Systems Limited - http://assimilationsystems.com
#
# The Assimilation software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Assimilation software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Assimilation Project software.  If not, see http://www.gnu.org/licenses/
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
cmdexists() {
  for dir in $(echo $PATH | tr ':' ' ')
  do
    if
      [ -f "$dir/$1" -a -x "$dir/$1" ]
    then
      echo "$dir/$1"
      return 0
    fi
  done
  return 1
}


dpkg_pkgs() {
  if
    cmdexists dpkg-query >/dev/null 2>&1
  then
    : OK
  else
    return
  fi
  printf '"deb":'
  comma='{
'
  dpkg-query --show --showformat='"${package;0}::${architecture;0}":"${version;0}"\n' 2>/dev/null |
  while
    read line
  do
    printf '%s' "${comma}${line}"
    comma=',
'
  done
  printf '}'
}

discover() {
    cat <<-!
	{
	  "discovertype": "packages",
	  "description": "Package information",
	  "host": "$(uname -n)",
	  "source": "$0",
	  "data": {
	!
  for pkgtype in dpkg_pkgs
  do
      $pkgtype
  done
  echo "}}"
}
discover
