#!/bin/sh
# vim: smartindent tabstop=4 shiftwidth=4 expandtab number
#
# This file is part of the Assimilation Project.
#
# Author: Alan Robertson <alanr@unix.sh>
# Copyright (C) 2013 - Assimilation Systems Limited
#
# Free support is available from the Assimilation Project community - http://assimproj.org
# Paid support is available from Assimilation Systems Limited - http://assimilationsystems.com
#
# The Assimilation software is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Assimilation software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the Assimilation Project software.  If not, see http://www.gnu.org/licenses/
#
#
#
#   List upstart job statuses
#   The special entry "#upstart" is true if upstart is installed running, and false otherwise
#
INITCTL=/sbin/initctl
UPSTARTLIST=""

have_upstart() {
  if
    [ ! -f "${INITCTL}" -o ! -x "${INITCTL}" ]
  then
    return 1
  else
      case "$("${INITCTL}" version)" in
        *'(upstart '*')')   return 0
      esac
  fi
  return 1
}

discover() {
    
    cat <<-!
	{
	  "discovertype": "upstart",
	  "description": "upstart job status",
	  "host": "$(uname -n)",
	  "source": "$0",
	  "data": {
	!
    if
        have_upstart
    then
        printf '	    "#upstart": true'
        comma=',\n	    '
        "${INITCTL}" list 2>/dev/null | sort -u |
        while
            read service status
        do
            case $status in
                start/*)      stat='true';;
                *)            stat='false';;
            esac
            printf ',\n\t     "%s": %s' "${service}" "${stat}"
        done
    else
        printf '	    "#upstart": false'
    fi
	printf '\n	}\n}\n'
}
        

discover
