# This is the original work of Jamie Nguyen.
#
# To the extent possible under law, Jamie Nguyen has waived all copyright
# and related or neighboring rights to this work.
#
# This work is published from: United Kingdom.
#
# See https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt

%global snapshot 20130707hgae4553edf8c9
%global enable_docs 0

%global cma_user    assimilation
%global cma_group   assimilation

%global _hardened_build 1

%if 0%{?rhel}
%global cma_rundir  %{_localstatedir}/run/assimilation
%global nano_rundir %{_localstatedir}/run/nanoprobe
%else
%global cma_rundir  /run/assimilation
%global nano_rundir /run/nanoprobe
%endif

Name:       assimilation-cma
Version:    0.1.0
Release:    0.25.%{snapshot}%{?dist}
Summary:    Collective Management Authority (CMA) for Assimilation

Group:      Applications/System
License:    GPLv3+
URL:        http://linux-ha.org/source-doc/assimilation/html/index.html
# Source0 is generated by running Source10, which pulls from the upstream
# version control repository.
Source0:    assimilation-%{snapshot}.tgz
Source1:    assimilation-cma.tmpfiles.conf
Source10:   assimilation-snapshot.sh
Source20:   assimilation-cma.service
Source30:   assimilation-cma.init
# A copy of the CC0 legal code taken from:
# https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt
# This waives all copyright for the following files:
# assimilation-0.1.0-cmake-typo.patch
# assimilation-cma.init
# assimilation-cma.service
# assimilation-cma.tmpfiles.conf
# assimilation-nanoprobe.init
# assimilation-nanoprobe.service
# assimilation-snapshot.sh
# assimilation-cma.spec
Source100:  legalcode.txt

# Fix a typo.
Patch0:     assimilation-0.1.0-cmake-typo.patch

%if 0%{?rhel}
BuildRequires: cmake28
%else
BuildRequires: cmake
%endif

BuildRequires: glib2-devel
BuildRequires: libpcap-devel
BuildRequires: pkgconfig
BuildRequires: python-devel
BuildRequires: python-ctypesgen
BuildRequires: python-py2neo < 1.5

Requires:         neo4j
Requires:         python-py2neo < 1.5
Requires:         assimilation-nanoprobe = 0:%{version}-%{release}
Requires(pre):    shadow-utils

%if 0%{?rhel}
Requires(post):   chkconfig
Requires(preun):  chkconfig
Requires(preun):  initscripts
Requires(postun): initscripts
%else
BuildRequires:    systemd
Requires(post):   systemd
Requires(preun):  systemd
Requires(postun): systemd
%endif

Obsoletes: assimilation < 0:0.1.0-0.2.20130303hg514
Provides:  assimilation = 0:%{version}-%{release}
Obsoletes: assimilation-cma-tests < 0:0.1.0-0.13.20130319hg80cec7a7e666
Provides:  assimilation-cma-tests = 0:%{version}-%{release}

%description
This package contains the Collective Management Authority (CMA) for
Assimilation.

Assimilation is designed to monitor systems and services on a network of
potentially unlimited size, without significant growth in centralized
resources. The work of monitoring is delegated uniformly in tiny pieces to
the various machines being monitored in a network-aware topology, minimizing
network overhead and being naturally geographically sensitive.

The main features include:
 - Can easily and massively scale
 - Monitor systems and services with near-zero overhead
 - Auto-configuration and integrated continuous Stealth Discovery™ of
   systems, services and dependencies
 - Easy to configure and manage

A normal installation consists of one instance of a Collective Management
Authority (CMA) and n+1 nanoprobes. Only one machine runs the CMA software,
but every machine being monitored (including the CMA itself) runs a copy of
the assimilation-nanoprobe daemon.

%package -n assimilation-nanoprobe
Group:         Applications/System
Summary:       Nanoprobe distributed monitoring agent for Assimilation
Source21:      assimilation-nanoprobe.service
Source31:      assimilation-nanoprobe.init
%if 0%{?rhel}
Requires(post):   chkconfig
Requires(preun):  chkconfig
Requires(preun):  initscripts
Requires(postun): initscripts
%else
Requires(post):   systemd
Requires(preun):  systemd
Requires(postun): systemd
%endif
Requires:         redhat-lsb-core
Requires:         wireless-tools

%description -n assimilation-nanoprobe
This package contains the nanoprobe distributed monitoring agent for
Assimilation.

Assimilation is designed to monitor systems and services on a network of
potentially unlimited size, without significant growth in centralized
resources. The work of monitoring is delegated uniformly in tiny pieces to
the various machines being monitored in a network-aware topology, minimizing
network overhead and being naturally geographically sensitive.

The main features include:
 - Can easily and massively scale
 - Monitor systems and services with near-zero overhead
 - Auto-configuration and integrated continuous Stealth Discovery™ of
   systems, services and dependencies
 - Easy to configure and manage

A normal installation consists of one instance of a Collective Management
Authority (CMA) and n+1 nanoprobes. Only one machine runs the CMA software,
but every machine being monitored (including the CMA itself) runs a copy of
the assimilation-nanoprobe daemon.

%if 0%{?enable_docs}
%package -n assimilation-doc
Group:         Documentation
Summary:       Documentation for assimilation
BuildRequires: doxygen
BuildRequires: graphviz

%description -n assimilation-doc
%{summary}.
%endif


%prep
%setup -q -n assimilation-%{snapshot}
%patch0 -p1


%build
mkdir -p build
pushd build
%if 0%{?rhel}
%cmake28 .. -DCMAKE_SKIP_BUILD_RPATH=1
%else
%cmake .. -DCMAKE_SKIP_BUILD_RPATH=1
%endif
popd

%if 0%{?enable_docs}
pushd build
make doc
popd
%endif


%install
pushd build
make install DESTDIR=%{buildroot}
popd

# Remove the upstream initscripts so we can replace with our own.
rm -rf %{buildroot}%{_sysconfdir}

%if 0%{?enable_docs}
mkdir -p %{buildroot}%{_docdir}/assimilation
cp -a build/doxygen/html %{buildroot}%{_docdir}/assimilation
%endif

%if 0%{?rhel}
install -p -D -m0755 %{SOURCE30} %{buildroot}%{_initddir}/assimilation-cma
install -p -D -m0755 %{SOURCE31} %{buildroot}%{_initddir}/assimilation-nanoprobe
%else
install -p -D -m0644 %{SOURCE20} %{buildroot}%{_unitdir}/assimilation-cma.service
install -p -D -m0644 %{SOURCE21} %{buildroot}%{_unitdir}/assimilation-nanoprobe.service
install -p -D -m0644 %{SOURCE1} %{buildroot}%{_prefix}/lib/tmpfiles.d/assimilation-cma.conf
%endif

mkdir -p %{buildroot}%{cma_rundir}
mkdir -p %{buildroot}%{nano_rundir}

mkdir -p %{buildroot}%{_libdir}
ln -sf %{_libdir}/assimilation/libassimilationclientlib.so \
    %{buildroot}%{_libdir}/libassimilationclientlib.so
ln -sf %{_libdir}/assimilation/libassimilationserverlib.so \
    %{buildroot}%{_libdir}/libassimilationserverlib.so

mkdir -p %{buildroot}%{python_sitearch}/assimilation/testcode
for i in filetest mainlooptest pinger; do
    install -p -D -m0755 build/testcode/"${i}" \
        %{buildroot}%{python_sitearch}/assimilation/testcode/"${i}"
done
sed -i '1i #!/bin/bash' testcode/grind.sh
install -p -D -m0755 testcode/grind.sh \
    %{buildroot}%{python_sitearch}/assimilation/testcode/grind.sh
install -p -D -m0644 testcode/valgrind-msgs.supp \
    %{buildroot}%{python_sitearch}/assimilation/testcode/valgrind-msgs.supp


%pre
getent group %{cma_group} > /dev/null || groupadd -r %{cma_group}
getent passwd %{cma_user} > /dev/null || \
    useradd -r -M -g %{cma_group} \
    -s /sbin/nologin -c "Assimilation Collective Management Authority" %{cma_user}
exit 0


%if 0%{?rhel}
%post
/sbin/chkconfig --add assimilation-cma

%preun
if [ $1 -eq 0 ] ; then
    /sbin/service assimilation-cma stop >/dev/null 2>&1
    /sbin/chkconfig --del assimilation-cma
fi

%postun
if [ $1 -ge 1 ] ; then
    /sbin/service assimilation-cma condrestart >/dev/null 2>&1 || :
fi

%post -n assimilation-nanoprobe
/sbin/ldconfig %{_libdir}/assimilation
/sbin/chkconfig --add assimilation-nanoprobe

%preun -n assimilation-nanoprobe
if [ $1 -eq 0 ] ; then
    /sbin/service assimilation-nanoprobe stop >/dev/null 2>&1
    /sbin/chkconfig --del assimilation-nanoprobe
fi

%postun -n assimilation-nanoprobe
/sbin/ldconfig %{_libdir}/assimilation
if [ $1 -ge 1 ] ; then
    /sbin/service assimilation-nanoprobe condrestart >/dev/null 2>&1 || :
fi

%else

%post
%systemd_post assimilation-cma.service

%preun
%systemd_preun assimilation-cma.service

%postun
%systemd_postun_with_restart assimilation-cma.service

%post -n assimilation-nanoprobe
/sbin/ldconfig
%systemd_post assimilation-nanoprobe.service

%preun -n assimilation-nanoprobe
%systemd_preun assimilation-nanoprobe.service

%postun -n assimilation-nanoprobe
/sbin/ldconfig
%systemd_postun_with_restart assimilation-nanoprobe.service
%endif


%files
%doc legal/COPYING README
%{python_sitearch}/assimilation
%{_sbindir}/cma
%attr(0755,%{cma_user},%{cma_group}) %dir %{cma_rundir}

%if 0%{?rhel}
%{_initddir}/assimilation-cma
%else
%{_unitdir}/assimilation-cma.service
%{_prefix}/lib/tmpfiles.d/assimilation-cma.conf
%endif

%files -n assimilation-nanoprobe
%doc legal/COPYING
%dir %{_libdir}/assimilation
%{_libdir}/assimilation/libassimilationclientlib.so
%{_libdir}/assimilation/libassimilationserverlib.so
%{_sbindir}/nanoprobe
%{_datadir}/assimilation
%attr(0755,root,root) %dir %{nano_rundir}
# Workaround for now.
%{_libdir}/libassimilationclientlib.so
%{_libdir}/libassimilationserverlib.so

%if 0%{?rhel}
%{_initddir}/assimilation-nanoprobe
%else
%{_unitdir}/assimilation-nanoprobe.service
%endif

%if 0%{?enable_docs}
%files -n assimilation-doc
%doc legal/COPYING
%{_docdir}/assimilation
%endif


%changelog
* Tue Jul 16 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.25.20130707hgae4553edf8c9
- update to hgae4553edf8c9
- add a missing BR

* Fri Jul 05 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.24.20130623hge529aa0d0e98
- Requires neo4j < 1.5

* Thu Jul 04 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.23.20130623hge529aa0d0e98
- do not start services by default
- add missing Short-Description to initscripts
- build with -DCMAKE_SKIP_BUILD_RPATH
- add missing shebang for testcode/grind.sh

* Tue Jul 02 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.22.20130623hge529aa0d0e98
- update to hge529aa0d0e98

* Fri Jun 21 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.21.20130610hga4584d5ba190
- update to hga4584d5ba190

* Mon Apr 15 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.20.20130415hgb175c7a2ecd3
- update to hgb175c7a2ecd3

* Mon Apr 15 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.19.20130414hg953f5c3a4e4b
- update to hg953f5c3a4e4b (v0.1.0-RC4)

* Sat Apr 06 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.18.20130405hg9923c7650d14
- update to hg9923c7650d14

* Sun Mar 31 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.17.20130329hg55163bd21d7c
- update to hg55163bd21d7c

* Wed Mar 27 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.16.20130323hg36236b3560f2
- fix a typo in clientlib/CMakeLists.txt
- make sure the headerfiles are sorted consistently when running
  genpybindings.py

* Tue Mar 26 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.15.20130323hg36236b3560f2
- update to hg36236b3560f2 (0.1.0-RC2)

* Sat Mar 23 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.14.20130323hg20185cf5bcb7
- update to hg20185cf5bcb7
- remove patches for building on RHEL 6 that have now been implemented upstream

* Thu Mar 21 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.13.20130319hg80cec7a7e666
- move assimilation-cma-tests files to assimilation-cma package

* Tue Mar 19 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.12.20130319hg80cec7a7e666
- add assimilation-cma-tests subpackage

* Tue Mar 19 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.11.20130319hg80cec7a7e666
- update to hg80cec7a7e666

* Mon Mar 18 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.10.20130318hg541
- update to hg541

* Sun Mar 17 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.9.RC1
- add redhat-lsb-core to assimilation-nanoprobe Requires

* Sun Mar 17 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.8.RC1
- fix scriptlets

* Sun Mar 17 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.7.RC1
- some more minor fixes to service files and initscripts

* Sun Mar 17 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.6.RC1
- minor fixes to service files and initscripts

* Sun Mar 17 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.5.RC1
- add missing ldconfig commands when building for EPEL

* Sun Mar 17 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.4.RC1
- update to upstream release 0.1.0-RC1

* Sat Mar 16 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.3.20130316hg532
- update to hg532
- fix ldconfig scriptlets
- add wireless-tools to assimilation-nanoprobe Requires

* Wed Mar 13 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.2.20130303hg514
- rename assimilation to assimilation-cma to match upstream

* Tue Mar 12 2013 Jamie Nguyen <jamielinux@fedoraproject.org> - 0.1.0-0.1.20130303hg514
- initial package
